#!/usr/bin/env ruby

require "fileutils"

FileUtils.rm(Dir.glob("output*"))

os = ENV['OS'] || nil
if os == nil
    system """ printf 'ERROR!
+--- Must provide OS to build! ---+
| Examples:                       |
|    OS=OSX build                 |
|    OS=WIN build                 |
+---------------------------------+'
"""
    abort
end

if os == 'OSX'
    osPath = '/Applications/Adobe Illustrator CC 2014/Startup Scripts/'

    if Dir.exists?(osPath)
        puts "working in #{osPath}"
        puts "removing any old installations"
        FileUtils.rm_r(Dir.glob("#{osPath}creatingDeftly*"))
    else
        Dir.mkdir osPath
        puts "created Startup Scripts folder in \n#{osPath}"
    end

    puts "copying in new installation"
    FileUtils.cp_r(Dir.glob('./creatingDeftly*'), Dir.glob("#{osPath}"))

    puts "running installation test..."
    `open -W -F -b com.adobe.illustrator testInstall.jsx`
end